import type { NextPage } from 'next'
import Image from 'next/image'
import Layout from '../components/Layout'

const Home: NextPage = () => {
  return (
    <Layout pageTitle='Home'>
      <Image src="/dio.png" width={200} height={200} alt='Dio from Grand Chase' />
      <h1>Welcome, Alvin!</h1>    
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit animi fugiat, labore, molestias repellendus perspiciatis architecto sit veritatis reiciendis libero fuga? Dolores officiis consequatur, temporibus dignissimos dicta, voluptatum quae illo deserunt dolorem sed ab impedit, quod distinctio est neque culpa minus id consequuntur necessitatibus? Iusto itaque aliquam consectetur fuga quam harum quaerat eum, animi error distinctio dignissimos repellendus dolor fugit corrupti voluptates, eius aut id explicabo a aliquid? Dignissimos, nemo accusantium quaerat illum quod maxime exercitationem placeat! Fugit totam facere excepturi animi iure. Optio voluptates soluta non accusantium quo corrupti id earum corporis aspernatur reprehenderit. Dignissimos autem cupiditate id ipsa.</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit animi fugiat, labore, molestias repellendus perspiciatis architecto sit veritatis reiciendis libero fuga? Dolores officiis consequatur, temporibus dignissimos dicta, voluptatum quae illo deserunt dolorem sed ab impedit, quod distinctio est neque culpa minus id consequuntur necessitatibus? Iusto itaque aliquam consectetur fuga quam harum quaerat eum, animi error distinctio dignissimos repellendus dolor fugit corrupti voluptates, eius aut id explicabo a aliquid? Dignissimos, nemo accusantium quaerat illum quod maxime exercitationem placeat! Fugit totam facere excepturi animi iure. Optio voluptates soluta non accusantium quo corrupti id earum corporis aspernatur reprehenderit. Dignissimos autem cupiditate id ipsa.</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit animi fugiat, labore, molestias repellendus perspiciatis architecto sit veritatis reiciendis libero fuga? Dolores officiis consequatur, temporibus dignissimos dicta, voluptatum quae illo deserunt dolorem sed ab impedit, quod distinctio est neque culpa minus id consequuntur necessitatibus? Iusto itaque aliquam consectetur fuga quam harum quaerat eum, animi error distinctio dignissimos repellendus dolor fugit corrupti voluptates, eius aut id explicabo a aliquid? Dignissimos, nemo accusantium quaerat illum quod maxime exercitationem placeat! Fugit totam facere excepturi animi iure. Optio voluptates soluta non accusantium quo corrupti id earum corporis aspernatur reprehenderit. Dignissimos autem cupiditate id ipsa.</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit animi fugiat, labore, molestias repellendus perspiciatis architecto sit veritatis reiciendis libero fuga? Dolores officiis consequatur, temporibus dignissimos dicta, voluptatum quae illo deserunt dolorem sed ab impedit, quod distinctio est neque culpa minus id consequuntur necessitatibus? Iusto itaque aliquam consectetur fuga quam harum quaerat eum, animi error distinctio dignissimos repellendus dolor fugit corrupti voluptates, eius aut id explicabo a aliquid? Dignissimos, nemo accusantium quaerat illum quod maxime exercitationem placeat! Fugit totam facere excepturi animi iure. Optio voluptates soluta non accusantium quo corrupti id earum corporis aspernatur reprehenderit. Dignissimos autem cupiditate id ipsa.</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit animi fugiat, labore, molestias repellendus perspiciatis architecto sit veritatis reiciendis libero fuga? Dolores officiis consequatur, temporibus dignissimos dicta, voluptatum quae illo deserunt dolorem sed ab impedit, quod distinctio est neque culpa minus id consequuntur necessitatibus? Iusto itaque aliquam consectetur fuga quam harum quaerat eum, animi error distinctio dignissimos repellendus dolor fugit corrupti voluptates, eius aut id explicabo a aliquid? Dignissimos, nemo accusantium quaerat illum quod maxime exercitationem placeat! Fugit totam facere excepturi animi iure. Optio voluptates soluta non accusantium quo corrupti id earum corporis aspernatur reprehenderit. Dignissimos autem cupiditate id ipsa.</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit animi fugiat, labore, molestias repellendus perspiciatis architecto sit veritatis reiciendis libero fuga? Dolores officiis consequatur, temporibus dignissimos dicta, voluptatum quae illo deserunt dolorem sed ab impedit, quod distinctio est neque culpa minus id consequuntur necessitatibus? Iusto itaque aliquam consectetur fuga quam harum quaerat eum, animi error distinctio dignissimos repellendus dolor fugit corrupti voluptates, eius aut id explicabo a aliquid? Dignissimos, nemo accusantium quaerat illum quod maxime exercitationem placeat! Fugit totam facere excepturi animi iure. Optio voluptates soluta non accusantium quo corrupti id earum corporis aspernatur reprehenderit. Dignissimos autem cupiditate id ipsa.</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit animi fugiat, labore, molestias repellendus perspiciatis architecto sit veritatis reiciendis libero fuga? Dolores officiis consequatur, temporibus dignissimos dicta, voluptatum quae illo deserunt dolorem sed ab impedit, quod distinctio est neque culpa minus id consequuntur necessitatibus? Iusto itaque aliquam consectetur fuga quam harum quaerat eum, animi error distinctio dignissimos repellendus dolor fugit corrupti voluptates, eius aut id explicabo a aliquid? Dignissimos, nemo accusantium quaerat illum quod maxime exercitationem placeat! Fugit totam facere excepturi animi iure. Optio voluptates soluta non accusantium quo corrupti id earum corporis aspernatur reprehenderit. Dignissimos autem cupiditate id ipsa.</p>
    </Layout>
  )
}

export default Home
